import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import cheerio from 'cheerio';
const inter = Inter({ subsets: ['latin'] });
import axios from 'axios';
import { useEffect, useState, useRef } from 'react';
import Table from '@/components/Table';
import fetchTables from '@/data/stats';

export default function Home(props) {
  // const tables = [];
  // const $ = cheerio.load(props.data);
  // $('table').each((i, el) => {
  //   tables.push($(el));
  // });

  console.log('props.tables', props);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {props.tables.map((t, i) => (
            <div key={i} style={{}}>
              <Table table={t} />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const tables = await fetchTables();

  return {
    props: { tables },
  };
}

// export async function getStaticProps() {
//   const { data } = await axios.get(
//     'https://www.maxpreps.com/in/alexandria/alexandria-monroe-tigers/athletes/gabe-mcguire/baseball/stats/?careerid=v9bof4vgp73dd'
//   );
//   const tables = [];
//   const d = [];

//   const $ = cheerio.load(data);
//   $('table').each((i, el) => {
//     tables.push($(el));
//   });

//   tables.forEach((t, i) => {
//     $(t)
//       .find('th')
//       .each((i, el) => {
//         d.push($(el).text());
//       });
//   });

//   // console.log($(tables[0]).find('tr').text());

//   return {
//     props: { d },
//   };
// }
